/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 监视通知携带受影响路径及健康状态；失败不能伪装成一次成功刷新。 */
export interface JsVaultEvent {
  /** changed、watch-error 或 index-error。 */
  status: string
  /** 已约束到当前库的相对路径，空列表表示需要完整刷新。 */
  paths: Array<string>
  /** 本次确实完成了监视后的索引校验。 */
  healthy: boolean
  /** 异常原因；成功事件不提供。 */
  message?: string
}
/**
 * 打开库并开始监视。
 *
 * `root` 是库目录，`index_dir` 是库外的派生索引与恢复目录。
 * 监视线程在防抖与索引刷新后，将 `on_changed` 投递给持有内核的 JS 线程。
 * 成功后替换当前库及其监视器；失败时保留原库。
 *
 * # Errors
 *
 * 打不开目录、索引或监视器时失败。
 */
export declare function vaultOpen(root: string, indexDir: string, onChanged: (...args: any[]) => any): void
/**
 * 关闭当前库并停止监视。
 *
 * # Errors
 *
 * 锁毒化时失败。
 */
export declare function vaultClose(): void
/**
 * 列出库内相对路径。
 *
 * # Errors
 *
 * 未打开库或读目录失败。
 */
export declare function vaultList(): Array<string>
/** 文件树条目，包含空文件夹。 */
export interface JsVaultEntry {
  /** 库内相对路径。 */
  path: string
  /** file 或 directory。 */
  kind: string
  /** 仅在草稿无法对应真实文件条目时设置。 */
  recoveryOnly?: boolean
}
/** 列出完整目录；未打开库或目录读取失败时返回错误。 */
export declare function vaultEntries(): Array<JsVaultEntry>
/** 创建空笔记或文件夹；非法类型、同名目标或磁盘失败时拒绝。 */
export declare function entryCreate(path: string, kind: string): JsRenameOutcome
/** 独占导入的附件位置和提交后警告。 */
export interface JsImportedAttachment {
  /** 实际库内路径，同名避让后可能与原文件名不同。 */
  path: string
  /** 文件已落盘后发生的索引或同步错误。 */
  warning?: string
}
/** 导入用户选择的附件字节，返回实际位置；路径、大小与写盘错误由内核传播。 */
export declare function attachmentImport(from: string, name: string, bytes: Buffer): JsImportedAttachment
/** 移入系统废纸篓；失败不退化为永久删除，未保存草稿阻止操作。 */
export declare function entryTrash(path: string): JsRenameOutcome
/** 获取经过库根校验的现有路径，只供主进程调用系统文件管理器。 */
export declare function entryPath(path: string): string
/**
 * 读取文件原始字节。
 *
 * # Errors
 *
 * 未打开库、越界或不存在。
 */
export declare function fileRead(rel: string): Buffer
/** 已持久化的恢复草稿。 */
export interface JsDraft {
  /** 普通草稿为最新内容；存在 editor 时为重建源码映射的原始字节。 */
  bytes: Buffer
  /** 原编辑基准；缺失表示新文件。 */
  base?: Buffer
  /** 版本化的编辑器恢复内容；没有时按普通 Markdown 字节恢复。 */
  editor?: string
}
/** 编辑器加载快照，文件删除时仍可恢复草稿。 */
export interface JsFileSnapshot {
  /** 磁盘内容；缺失时通过 disk_error 区分删除与读取失败。 */
  disk?: Buffer
  /** 原路径不可读时保留草稿，并携带原因。 */
  diskError?: string
  /** 尚未提交的编辑。 */
  draft?: JsDraft
}
/**
 * 获取 `rel` 的磁盘内容与恢复草稿。
 *
 * # Errors
 *
 * 未打开库、越界或读取失败。
 */
export declare function fileSnapshot(rel: string): JsFileSnapshot
/**
 * 持久化带版本的编辑恢复数据，保持原笔记字节不变。
 *
 * # Errors
 * 未打开库、路径或数据非法、恢复记录冲突或数据库不可写。
 */
export declare function filePreserveDraft(rel: string, source: Buffer, expected: Buffer | undefined | null, editor: string): void
/** 文件提交结果，冲突时附带磁盘版本。 */
export interface JsWriteResult {
  /** `saved` 或 `conflict`。 */
  status: string
  /** 冲突的磁盘字节；缺失也可能表示文件被删除。 */
  disk?: Buffer
  /** 已提交后的同步、索引或清理警告。 */
  warning?: string
}
/**
 * 按 `expected` 基准保存 `bytes`，返回提交状态或冲突。
 *
 * # Errors
 *
 * 未打开库、越界、草稿持久化或内容提交失败。
 */
export declare function fileWrite(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): JsWriteResult
/** 新副本的路径与提交后警告。 */
export interface JsSavedCopy {
  /** 实际创建的相对路径。 */
  path: string
  /** 内容已保存后的警告。 */
  warning?: string
}
/**
 * 将当前 `bytes` 写入唯一命名的新副本，`expected` 用于恢复基准。
 *
 * # Errors
 *
 * 未打开库、路径非法或副本提交失败。
 */
export declare function fileWriteCopy(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): JsSavedCopy
/**
 * 解析链接目标。
 *
 * `kind` 为 `wiki` 或 `md`。
 *
 * # Errors
 *
 * 未打开库或 kind 非法。
 */
export declare function linksResolve(from: string, raw: string, kind: string): string | null
/** 一条索引中的链接。 */
export interface JsLinkRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 链接原文中的目标。 */
  toRaw: string
  /** 解析到的路径；死链为 `null`。 */
  toPath?: string
  /** `wiki` 或 `md`。 */
  kind: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
}
/** 一条已链接或未链接提及。 */
export interface JsMentionRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 源文件展示标题。 */
  fromTitle: string
  /** 源文件内容修改时间（自纪元起的纳秒）。 */
  mtime: number
  /** 命中区间起点（含）。 */
  startByte: number
  /** 命中区间终点（不含）。 */
  endByte: number
  /** 命中所在段落。 */
  snippet: string
  /** `linked` 或 `unlinked`。 */
  kind: string
  /** 已链接时为 `wiki`/`md`；未链接为 `null`。 */
  linkKind?: string
  /** 已链接为链接原文目标；未链接为命中文本。 */
  toRaw: string
}
/** 指向一篇笔记的已链接与未链接提及。 */
export interface JsMentions {
  /** 索引里的入链。 */
  linked: Array<JsMentionRecord>
  /** 正文里尚未做成链接的出现。 */
  unlinked: Array<JsMentionRecord>
}
/**
 * 指向 `path` 的入链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksTo(path: string): Array<JsLinkRecord>
/**
 * `path` 的出链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksFrom(path: string): Array<JsLinkRecord>
/**
 * 指向 `path` 的已链接提及与未链接提及。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexMentionsTo(path: string): JsMentions
/** 文件已经完成改名，索引或日志清理可能仍需重试。 */
export interface JsRenameOutcome {
  /** 提交后的警告；无警告时缺失。 */
  warning?: string
}
/**
 * 将 `from` 改名为 `to` 并更新全库链接，返回提交后的警告。
 *
 * # Errors
 *
 * 未打开库、目标已存在或写盘失败。
 */
export declare function entryRename(from: string, to: string): JsRenameOutcome
