/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 打开库并开始监视。
 *
 * `on_changed` 在防抖后的监视线程上调用，主进程应据此通知渲染进程。
 *
 * # Errors
 *
 * 打不开目录、索引或监视器时失败。
 */
export declare function vaultOpen(root: string, indexDir: string, onChanged: (...args: any[]) => any): void
/**
 * 关闭当前库并停止监视。
 *
 * # Errors
 *
 * 锁毒化时失败。
 */
export declare function vaultClose(): void
/**
 * 列出库内相对路径。
 *
 * # Errors
 *
 * 未打开库或读目录失败。
 */
export declare function vaultList(): Array<string>
/**
 * 读取文件原始字节。
 *
 * # Errors
 *
 * 未打开库、越界或不存在。
 */
export declare function fileRead(rel: string): Buffer
/**
 * 原子写入文件并重建索引。
 *
 * # Errors
 *
 * 未打开库或越界。
 */
export declare function fileWrite(rel: string, bytes: Buffer): void
/**
 * 解析链接目标。
 *
 * `kind` 为 `wiki` 或 `md`。
 *
 * # Errors
 *
 * 未打开库或 kind 非法。
 */
export declare function linksResolve(from: string, raw: string, kind: string): string | null
/** 一条索引中的链接。 */
export interface JsLinkRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 链接原文中的目标。 */
  toRaw: string
  /** 解析到的路径；死链为 `null`。 */
  toPath?: string
  /** `wiki` 或 `md`。 */
  kind: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
}
/** 一条已链接或未链接提及。 */
export interface JsMentionRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 源文件展示标题。 */
  fromTitle: string
  /** 源文件内容修改时间（自纪元起的纳秒）。 */
  mtime: number
  /** 命中区间起点（含）。 */
  startByte: number
  /** 命中区间终点（不含）。 */
  endByte: number
  /** 命中所在段落。 */
  snippet: string
  /** `linked` 或 `unlinked`。 */
  kind: string
  /** 已链接时为 `wiki`/`md`；未链接为 `null`。 */
  linkKind?: string
  /** 已链接为链接原文目标；未链接为命中文本。 */
  toRaw: string
}
/** 指向一篇笔记的已链接与未链接提及。 */
export interface JsMentions {
  /** 索引里的入链。 */
  linked: Array<JsMentionRecord>
  /** 正文里尚未做成链接的出现。 */
  unlinked: Array<JsMentionRecord>
}
/**
 * 指向 `path` 的入链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksTo(path: string): Array<JsLinkRecord>
/**
 * `path` 的出链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksFrom(path: string): Array<JsLinkRecord>
/**
 * 指向 `path` 的已链接提及与未链接提及。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexMentionsTo(path: string): JsMentions
/**
 * 改名并更新全库链接。
 *
 * # Errors
 *
 * 未打开库、目标已存在或写盘失败。
 */
export declare function entryRename(from: string, to: string): void
