[workspace]
resolver = "2"
members = ["crates/nous-core", "crates/nous-napi"]

[workspace.package]
edition = "2021"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
